image: $CI_REGISTRY/fcavalieri/jobrunr/ci:v0.0.5

before_script:
  - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle
    - .npm

build:
  stage: build
  script:
    - (cd core/src/main/resources/org/jobrunr/dashboard/frontend && npm install --cache $CI_PROJECT_DIR/.npm --prefer-offline)
    - (cd core/src/main/resources/org/jobrunr/dashboard/frontend && npm run build)
    - ./gradlew --no-daemon --info clean assemble

test:
  stage: test
  script:
    - (cd core/src/main/resources/org/jobrunr/dashboard/frontend && npm install --cache $CI_PROJECT_DIR/.npm --prefer-offline)
    - (cd core/src/main/resources/org/jobrunr/dashboard/frontend && npm run build)
    - ./gradlew --no-daemon -info build
  artifacts:
    paths:
      - /tmp/reports/core/index.html
      - /tmp/reports

publish:
  stage: publish
  script:
    - (cd core/src/main/resources/org/jobrunr/dashboard/frontend && npm install --cache $CI_PROJECT_DIR/.npm --prefer-offline)
    - (cd core/src/main/resources/org/jobrunr/dashboard/frontend && npm run build)
    - ./gradlew --no-daemon -info publish
  only:
    - fc-master
    
stages:
  - build
  - test
  - publish

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never  # Prevent pipeline run for push event
    - when: always # Run pipeline for all other cases
