image: $CI_REGISTRY/fcavalieri/jobrunr/ci:v1.0.0

variables:
  DOCKER_HOST: "tcp://localhost:2375"
  DOCKER_OPTIONS: "--tls=false --storage-driver overlay2 --data-root /var/lib/docker --registry-mirror http://192.168.178.219:5000 --registry-mirror http://192.168.178.220:5000"

before_script:
  - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle
    - .npm

build:
  stage: build
  script:
    - (cd core/src/main/resources/org/jobrunr/dashboard/frontend && npm install --cache $CI_PROJECT_DIR/.npm --prefer-offline)
    - (cd core/src/main/resources/org/jobrunr/dashboard/frontend && npm run build)
    - ./gradlew --no-daemon --info clean assemble

core:
  stage: test
  script:
    - /start-docker.sh $DOCKER_OPTIONS
    - (cd core/src/main/resources/org/jobrunr/dashboard/frontend && npm install --cache $CI_PROJECT_DIR/.npm --prefer-offline)
    - (cd core/src/main/resources/org/jobrunr/dashboard/frontend && npm run build)
    - ./gradlew --no-daemon core:test
  artifacts:
    paths:
      - /tmp/reports/core/index.html
      - /tmp/reports

other:
  stage: test
  script:
    - /start-docker.sh $DOCKER_OPTIONS
    - (cd core/src/main/resources/org/jobrunr/dashboard/frontend && npm install --cache $CI_PROJECT_DIR/.npm --prefer-offline)
    - (cd core/src/main/resources/org/jobrunr/dashboard/frontend && npm run build)
    - ./gradlew --no-daemon test -x core:test
  artifacts:
    paths:
      - /tmp/reports/core/index.html
      - /tmp/reports

publish:
  stage: publish
  script:
    - /start-docker.sh $DOCKER_OPTIONS
    - (cd core/src/main/resources/org/jobrunr/dashboard/frontend && npm install --cache $CI_PROJECT_DIR/.npm --prefer-offline)
    - (cd core/src/main/resources/org/jobrunr/dashboard/frontend && npm run build)
    - ./gradlew --no-daemon -info publish
  only:
    - fc-master
    
stages:
  - build
  - test
  - publish

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never  # Prevent pipeline run for push event
    - when: always # Run pipeline for all other cases
