name: Bug report
description: Create a bug report to help us improve JobRunr. 
title: "[BUG]"
assignees:
  - rdehuyss
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! As this is an open-source project where we try to make a living from, 
        we kindly ask you to have a **complete Github Personal Profile** (Name and Company details or LinkedIn Profile). It's always nice to 
        know to whom we're talking to and providing free support to. If your Github Profile is not complete, we will probably close 
        the issue without answering. For more info, read this excellent blog post about [open-source etiquette](https://www.yegor256.com/2020/07/29/open-source-etiquette.html).
  - type: input
    id: version
    attributes:
      label: JobRunr Version
      description: What version of JobRunr are you running?
      placeholder: ex. 5.3.1
    validations:
      required: true
  - type: input
    id: jdk-version
    attributes:
      label: JDK Version
      description: Which JRE/JDK are you using?
      placeholder: ex. OpenJDK 1.8.0_292
    validations:
      required: true
  - type: input
    id: storage-provider
    attributes:
      label: Your SQL / NoSQL database
      description: Which database are you using?
      placeholder: ex. Postgres 9 / MongoDB 4.4
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How to reproduce?
      description: Provide a simple Github project or code fragment which shows how to reproduce the issue (ideally a Github repo).
      placeholder: How can we reproduce the issue?
      value: >
         ```java
            BackgroundJob.enqueue(() -> service.helpMe());
         ```
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
#  - type: checkboxes
#    id: terms
#    attributes:
#      label: Code of Conduct
#      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
#      options:
#        - label: I agree to follow this project's Code of Conduct
#          required: true
